#!/bin/sh

# Copyright (c) 2021 Pietro Cerutti <gahr@gahr.ch>
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

set -euf

keyid=bitwarden
search_term=""

bwgetdir=~/.config/bwget
bwgetcache="$bwgetdir"/bw.gpg

jq_blue="\"\u001b[34m\""
jq_yellow="\"\u001b[33m\""
jq_green="\"\u001b[32m\""
jq_rst="\"\u001b[0m\""
jq_nl="\"\n\""

sh_red='\033[0;31m'
sh_rst='\033[0;0m'

die_header()
{
    title="$1"
    # shellcheck disable=SC2059
    printf "${sh_red}"
    printf "%s" "${title}"
    # shellcheck disable=SC2059
    printf "${sh_rst}"
}

die()
{
    die_header "$1"
    printf ": %s\n" "$2"
    exit 1
}

die_nl()
{
    die_header "$1"
    printf "\n%s\n" "$2"
    exit 1
}


sync()
{

    if ! gpg --quiet --list-keys "$keyid" > /dev/null 2>&1; then
        die "PG error" "cannot encrypt to $keyid"
    fi

    session=""
    status=$(bw status | jq -r .status)
    case "$status" in
        unauthenticated)
            session="$(bw login --raw)"
            ;;
        locked)
            session="$(bw unlock --raw)"
            ;;
        unlocked)
            # This means we probably have BW_SESSION in the env
            ;;
        *)
            die "Unexpected status" "$status"
            exit 1
            ;;
    esac

    bw_cmd=bw
    if [ -n "$session" ]; then
        bw_cmd="${bw_cmd} --session $session"
    fi

    $bw_cmd sync
    $bw_cmd list items | \
        gpg --encrypt --recipient "$keyid" --output "$bwgetcache"
}

check_sync()
{
    if [ ! -e "$bwgetcache" ]; then
        sync
    fi
}

check_config_dir()
{
    if [ ! -d "$bwgetdir" ]; then
        mkdir -p "$bwgetdir"
    fi
}

format()
{
    jq -r "
        ${jq_blue} + .name + ${jq_rst} +
        \" [\" + ${jq_green} + .id + ${jq_rst} + \"]\" + ${jq_nl} +
        ${jq_yellow} + \"Username\" + ${jq_rst} + \": \" + .login.username + ${jq_nl} +
        ${jq_yellow} + \"Password\" + ${jq_rst} + \": \" + .login.password + ${jq_nl} +
        ${jq_yellow} + \"URL     \" + ${jq_rst} + \": \" + .login.uris[0].uri + ${jq_nl} +
        ${jq_yellow} + \"Notes   \" + ${jq_rst} + \": \" + .notes"
}

limit()
{
    jq ".[] | select(.name|test(\"$search_term\"; \"i\"))"
}

dump()
{
    gpg --quiet --decrypt "$bwgetcache"
}

usage()
{
    echo "Usage: $0 [options] command [args]"
    echo ""
    echo "Options"
    echo "    --keyid <id>     Use <id> as the recipient for encryption"
    echo ""
    echo "Command"
    echo "    item <search>    Search and dump an item"
    echo "    user <search>    Search and dump the username of an item"
    echo "    pass <search>    Search and dump the password of an item"
    echo "    dump             Dump the local cache in JSON format"
    echo "    sync             Synchronize with remote Bitwarden vault"
    echo "    help             Display this help page"
    echo ""
    exit 1
}

cmd_dump()
{
    check_sync
    dump
}

cmd_sync()
{
    sync
}

cmd_item()
{
    check_sync
    data=$(dump | limit)
    check_any "$data"
    echo "$data" | format
}

check_single()
{
    data="$1"
    len=$(echo "$data" | jq -c '.' | wc -l)
    if [ "$len" -gt 1 ]; then
        die_nl "Multiple matches" "$(echo "$data" | jq -r '"* " + .name')"
    fi
}

check_any()
{
    data="$1"
    len=$(echo "$data" | jq -c '.' | wc -l)
    if [ "$len" -eq 0 ]; then
        die "No matches" "$search_term"
    fi
}

cmd_user()
{
    check_sync
    data=$(dump | limit)
    check_any "$data"
    check_single "$data"
    echo "$data" | jq -r .login.username
}

cmd_pass()
{
    check_sync
    data=$(dump | limit)
    check_any "$data"
    check_single "$data"
    echo "$data" | jq -r .login.password
}

main()
{
    check_config_dir

    cmd=""
    while [ $# -gt 0 ]; do
        case "$1" in
            --keyid)
                [ $# -lt 2 ] && usage
                keyid="$2"
                shift 2
                ;;
            user|pass|item)
                [ $# -lt 2 ] || [ -n "$cmd" ] && usage
                cmd=cmd_$1
                search_term="$2"
                shift 2
                ;;
            sync)
                [ -n "$cmd" ] && usage
                cmd=cmd_sync
                shift
                ;;
            dump)
                [ -n "$cmd" ] && usage
                cmd=cmd_dump
                shift
                ;;
            *)
                die_nl "Invalid argument: $1" "$(usage)"
                ;;
        esac
    done

    [ -z "$cmd" ] && usage

    "$cmd"
}

main "$@"
